pipelines:
  - name: local
#    sources:
#      - type: file
#        name: demo
#        paths:
#          - /tmp/log/*.log
#        fields:
#          topic: "loggie"
#        multi:
#          active: true
#          pattern: (?<=x)y

    sources:
      - type: dev
        name: demo
        eventsTotal: 100000
        byteSize: 1024
        qps: 1000
    queue:
      type: persisted
#      maxFileBytes: 10MB
#      batchBytes: 1MB

    sink:
      type: dev
      printMetrics: true
      printMetricsInterval: 10s
      resultStatus: fail